updating imports
552ACNS/odst pull request #142
Opened 2022-03-30 19:35 UTC by ericcater

Should be no @odst/types or other GQL imports in services and no prisma imports in resolver

2022-03-31 01:43 UTC, yurisim commented on .eslintrc.json
> +      "files": ["*.resolver.ts"],
Add a message to the error to explain why it shouldn't be there, see,

![image](https://user-images.githubusercontent.com/26447240/160959342-0530b803-0a30-4051-b5a2-b713ce235434.png)

https://eslint.org/docs/rules/no-restricted-imports

2022-03-31 01:45 UTC, yurisim requested changes
add a message to the rules, otherwise good job

2022-04-05 15:12 UTC, yurisim approved these changes

2022-04-05 15:17 UTC, yurisim commented on .eslintrc.json
> +                "message": "Do not import types from @odst/types in servicer, use prisma types instead (or greneted gql if in frontend)"
:( greneted

2022-04-05 15:19 UTC, yurisim requested changes
greneted

2022-04-05 15:21 UTC, ericcater commented on .eslintrc.json
> +                "message": "Do not import types from @odst/types in servicer, use prisma types instead (or greneted gql if in frontend)"
I know what I siad

2022-04-05 15:29 UTC, merged