Odst 105 admins cc dashboard page
552ACNS/odst pull request #144
Opened 2022-03-31 19:29 UTC by BrendenMcGrew

2022-03-31 19:51 UTC, ericcater requested changes

2022-03-31 19:51 UTC, ericcater commented on package.json
> +    "npm": "^8.5.5",
Probably shouldn't be here

2022-04-01 14:05 UTC, ericcater approved these changes

2022-04-04 04:35 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161474556-d54747ea-0059-4a5d-b803-ee37dff8d314.png)
Don't spam everyone like this please.

2022-04-04 07:00 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161489902-783659e1-f5a4-4b3a-942a-481b68bbda13.png)

Please just use a stylized mat-card, this isn't maintainable.

If you ever notice you duplicate styles, use a apply directive. This is hard to read,
https://tailwindcss.com/docs/reusing-styles

2022-04-04 07:02 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161490265-1bd3631a-92c0-4f0d-af3c-a14d475aecd6.png)
Don't use such a generic name

2022-04-04 07:06 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161490785-c2b70992-c26a-4cf3-9fd6-da37ea5d492b.png)

the query itself belongs in the servicer, don't call apollo in the component.ts.

However, this is correct, call the other shit in the backend.

2022-04-04 07:22 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161493406-a27a2fbd-58f7-4e5c-b764-787f600410fa.png)

- [ ] Top margins looks REALLY bad, they are nearly nonexistent

2022-04-04 07:24 UTC, yurisim commented
Clicking on these,

![image](https://user-images.githubusercontent.com/26447240/161493751-08ec1fde-44d2-4c11-967e-de60d3f682f8.png)

Should get you to the right pages. It should be active by now in dev

2022-04-04 07:31 UTC, yurisim requested changes
please resolve comments

2022-04-04 07:37 UTC, yurisim commented
Edges don't look right,
![image](https://user-images.githubusercontent.com/26447240/161495932-0a0b5359-a60a-41ff-91b4-1c7b327bd519.png)

![image](https://user-images.githubusercontent.com/26447240/161496011-ae404d46-5648-42e7-9f86-19a5231a5ed0.png)

2022-04-04 19:06 UTC, ericcater approved these changes

2022-04-06 13:34 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161493105-7a027f1d-3d11-41d8-8e2b-1a618edce9cd.png)

- [ ] Some elements are left aligned at random intervals, check your break points.
- [ ] Keep verbiage consistent, "Due" for "Unresolved?"

2022-04-07 15:10 UTC, pmeskridge approved these changes

2022-04-12 21:03 UTC, Mikehickey7 commented on apps/ods/src/app/dashboard/dashboard.component.scss
> +.card {
Put it in line ten and instead of using scss

2022-04-12 21:20 UTC, Mikehickey7 commented on package.json
> +    "@nrwl/angular": "13.9.6",
Did you mean to upgrade?

2022-04-12 21:21 UTC, Mikehickey7 approved these changes
looks good

2022-04-12 21:25 UTC, BrendenMcGrew commented on package.json
> +    "@nrwl/angular": "13.9.6",
Yes

2022-04-13 14:31 UTC, merged