Odst survey
552ACNS/odst pull request #145
Opened 2022-04-01 17:20 UTC by Mikehickey7

Still need to connect to Jira Story with this branch

-Created form folder 
     -verification of fields filled in before submit
     -successfully queries surveys to connect or create survey
     -successfully connects or creates unique questions
TODO: need to submit answers still along with surveryResponse

2022-04-01 18:09 UTC, ericcater requested changes

2022-04-04 09:33 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161516357-c6238ed4-6441-454a-ba38-e31d2d58275b.png)

2022-04-04 09:41 UTC, yurisim commented on apps/ods-api/schema.prisma
> +  prompt  String   @unique
Need to change the other seed scripts if you are going to do this.

2022-04-04 09:59 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161520993-1ec65b15-d5bf-4774-bd48-0d383580d854.png)
 idk if you guys are trolling but if stuff like this leaks  into production it makes us look bad :/

2022-04-04 10:00 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161521084-ea7f5301-6885-41ee-a549-c23fcdc09cb4.png)

Try to have the route be somewhat related to the module in naming

2022-04-04 10:04 UTC, yurisim commented
Did you guys check to see what this looks like @ different screen sizes before submitting?

![image](https://user-images.githubusercontent.com/26447240/161521926-cacb6a2e-989b-42a2-b235-10f7e83382a6.png)

2022-04-04 10:06 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161522151-4ed949de-6479-4d5d-b483-5fe90bd72aa3.png)

Instead of calling it all over the place, wrap the entire thing in 1 div and make the child elements fit to size. Don't duplicate CSS like this

2022-04-04 10:12 UTC, yurisim commented
![image](https://user-images.githubusercontent.com/26447240/161523147-510fe8f2-395a-490e-a689-59549567ae98.png)

Thought we said submit button on top?

2022-04-04 10:20 UTC, yurisim commented
Be consistent

![image](https://user-images.githubusercontent.com/26447240/161524518-e66f89da-1fb0-4014-81a4-6e7b0d01f521.png)

2022-04-12 18:51 UTC, yurisim commented on .github/workflows/ci.yml
> +        run: yarn nx run-many --target=prisma-generate --all
Revert these changes

2022-04-12 18:55 UTC, sayntonge commented on .github/workflows/ci.yml
> +        run: yarn nx run-many --target=prisma-generate --all
no u

2022-04-12 18:55 UTC, yurisim commented on apps/ods-api/src/prisma/singleton.ts
> +import { mockDeep, mockReset, DeepMockProxy } from 'jest-mock-extended';
Delete this file

2022-04-13 12:53 UTC, closed without merging