only return surveyResponses in current user's org
552ACNS/odst pull request #185
Opened 2022-04-25 19:52 UTC by ericcater

2022-04-26 18:25 UTC, yurisim requested changes
Don't think the survey responses are being shown

2022-04-26 18:25 UTC, yurisim commented on apps/ods-api/src/surveyResponse/surveyResponse.service.ts
> +        where: surveyResponseWhereUniqueInput,
Good catch :)

2022-04-26 18:25 UTC, yurisim commented on apps/ods-api/src/surveyResponse/surveyResponse.service.ts
> +    return Promise.all([unresolvedCount, overdueCount, resolvedCount]);
This is better! Nice.

2022-04-27 13:38 UTC, ericcater commented on apps/ods-api/src/surveyResponse/surveyResponse.service.ts
> +    return Promise.all([unresolvedCount, overdueCount, resolvedCount]);
Changed it again, I think the newest way is best

2022-04-27 20:20 UTC, yurisim requested changes
Please merge dev

2022-04-27 20:20 UTC, yurisim commented on apps/ods-api/src/surveyResponse/surveyResponse.resolver.ts
> +  //TODO findUnqiue is called from frontend, not sure how to prevent commanders from looking at other orgs' responses
find findUnqiue :(

2022-04-29 18:57 UTC, ericcater commented
> Please work with @Mikehickey7 to verify that responses show up in certain profiles and NOT others using UUIDs.
> 
> This is part of issue 155. It's marked as "done" on Jira but this issue (154) is part of it.

TGYTFYTYF

2022-05-04 16:17 UTC, yurisim submitted a review, later dismissed

2022-05-04 16:26 UTC, yurisim approved these changes

2022-05-04 16:29 UTC, merged

2022-05-04 19:18 UTC, yurisim commented on apps/ods/src/app/survey-questions/survey-questions.component.ts
>        .subscribe(({ data }) => {
may need to revert this change. Why did we do this again? Goni doesn't remember.

2022-05-04 19:18 UTC, yurisim commented on apps/ods/src/app/survey-questions/survey-questions.component.ts
>        .subscribe(({ data }) => {
may need to revert this change. Why did we do this again? Goni doesn't remember.