Odst 125 admin cc request an account so that i can monitor a specific squadron group wing
552ACNS/odst pull request #199
Opened 2022-04-29 18:41 UTC by Mikehickey7

Password has regex on it, however the rules are not clear yet, this will be solved with the implementation of the password-strength library

2022-04-29 19:21 UTC, yurisim requested changes
Please check that e2e tests pass

2022-05-02 15:47 UTC, yurisim commented on apps/ods-api/prisma-seed.ts
> +  const userCreateInputs: Prisma.UserCreateInput[] = [
Why is this here?

2022-05-02 15:55 UTC, REDRICK696 commented on apps/ods-api/prisma-seed.ts
> +  const userCreateInputs: Prisma.UserCreateInput[] = [
idk

2022-05-02 17:15 UTC, yurisim commented on apps/ods/src/app/login/login.component.html
> +      <p class="underline text-right" [routerLink]="['/request-account']">
Use the primary color styling to make it obvious that this is a link

2022-05-02 17:36 UTC, yurisim commented on libs/shared/angular/src/lib/passwordValidator.service.ts
> +    'Password must be between 8 and 48 characters, and contain at least one uppercase letter, one lowercase letter, one number and one special character',
Specify what allowed types of special characters in this string.

2022-05-02 17:44 UTC, yurisim requested changes
Fix requested changes please

2022-05-02 18:44 UTC, yurisim commented on libs/shared/angular/src/lib/passwordValidator.service.ts
> +    'Password must be between 8 and 48 characters, and contain at least one uppercase letter, one lowercase letter, one number and one special character',
![image](https://user-images.githubusercontent.com/26447240/166306307-c7a8576a-393c-4722-b361-cdfa482dc4e8.png)

2022-05-04 12:55 UTC, yurisim requested changes

2022-05-04 12:55 UTC, yurisim commented on apps/ods/src/app/request-account/request-account.component.ts
> +    { validator: CustomValidators.checkPasswords }
Fix the deprecated custom validator syntax.

https://blog.angular-university.io/angular-custom-validators/

2022-05-06 13:42 UTC, yurisim approved these changes

2022-05-06 13:42 UTC, yurisim commented on apps/ods/src/app/request-account/request-account.component.spec.ts
> +        MatOptionModule,
Is this needed?

2022-05-06 13:47 UTC, merged