added jira issues for todos
552ACNS/odst pull request #282
Opened 2022-06-21 21:06 UTC by ericcater

# To be Completed by the Pull Requester

### Checklist:

- [x] I have performed a self-review of my code to ensure that unintended code is not introduced.
- [x] I have commented my code, particularly in hard-to-understand areas to ensure that the next group of developers can understand my code.
- [x] I have added tests (if appropriate) that prove my fix/feature functions so that future modifications to the code do not break my additions.

### Description:

Added jira issues for todos

### Type of change (Pick Any)

4. Documentation update. Example: new setup instructions for a new feature.

### How Has This Been Tested?

N/A

---

# To be Completed By Reviewers

Reviewer # 01
- [x] I have performed a review of the code and checked for possible unintentional edits.
- [x] I concur with the amount of comments made.
- [x] I concur with the amount of tests made.

Reviewer # 02
- [ ] I have performed a review of the code and checked for possible unintentional edits.
- [ ] I concur with the amount of comments made.
- [ ] I concur with the amount of tests made.

2022-06-21 21:11 UTC, Mikehickey7 approved these changes

2022-06-21 21:12 UTC, Mikehickey7 requested changes
didnt pass pipeline

2022-06-22 17:56 UTC, yurisim approved these changes

2022-06-22 18:22 UTC, Mikehickey7 approved these changes

2022-06-22 18:22 UTC, Mikehickey7 commented
This is the most amazing stuff ive ever seen. Keep up the good work person

2022-06-22 19:03 UTC, merged