Odst 253 resolution tags for responses
552ACNS/odst pull request #286
Opened 2022-06-22 20:09 UTC by BrendenMcGrew

# To be Completed by the Pull Requester

### Checklist:

- [ ] I have performed a self-review of my code to ensure that unintended code is not introduced.
- [ ] I have commented my code, particularly in hard-to-understand areas to ensure that the next group of developers can understand my code.
- [ ] I have added tests (if appropriate) that prove my fix/feature functions so that future modifications to the code do not break my additions.

### Description:

- Please include a summary of the changes and the related issue.
- List any NEW dependencies that are required for this change.

### Type of change (Pick Any)

1. Bug fix. Non-breaking change which fixes an issue, example: swapping the order of numbers on a UI.

2. New feature. Non-breaking change which adds functionality, example: new page on the frontend.

3. Breaking change. Fix or feature that would cause existing functionality to not work as expected, example: API change that requires dependent projects to be updated.

4. Documentation update. Example: new setup instructions for a new feature.

### How Has This Been Tested?

Describe the tests that you created if applicable. Use N/A if no tests were created.

---

# To be Completed By Reviewers

Reviewer # 01
- [ ] I have performed a review of the code and checked for possible unintentional edits.
- [ ] I concur with the amount of comments made.
- [ ] I concur with the amount of tests made.

Reviewer # 02
- [ ] I have performed a review of the code and checked for possible unintentional edits.
- [ ] I concur with the amount of comments made.
- [ ] I concur with the amount of tests made.

2022-06-22 20:43 UTC, ericcater approved these changes

2022-06-24 20:14 UTC, yurisim requested changes
Fix conflicts

2022-06-27 16:27 UTC, ericcater approved these changes

2022-06-27 19:22 UTC, yurisim commented on apps/ods/src/app/responses/responses.component.ts
> +  //region Main functions
Either remove this or add additional regions but this doesn't block the PR, just something I noticed.

2022-06-27 19:52 UTC, yurisim commented on apps/ods/src/app/responses/select-tags/select-tags.component.spec.ts
> +    console.log(expected.length);
Remove these console.logs

2022-06-27 19:53 UTC, yurisim commented on apps/ods/src/app/responses/select-tags/select-tags.component.ts
> +  // eslint-disable-next-line @angular-eslint/component-selector
what is this disabling?

2022-06-27 19:53 UTC, yurisim commented on apps/ods/src/app/responses/select-tags/select-tags.component.ts
> +   * @param event
these params can still be commented

2022-06-27 19:54 UTC, yurisim commented on src/apps/ods-api/src/tag/tag.module.ts
> +export class TagModule {}
You def did not mean to commit this

2022-06-27 19:55 UTC, yurisim requested changes
There are some unintended changes in this.

2022-06-27 20:02 UTC, Mikehickey7 approved these changes
looks amazing, i found no errors, but fix the errors sim found

2022-06-27 20:28 UTC, BrendenMcGrew commented on apps/ods/src/app/responses/select-tags/select-tags.component.ts
> +  // eslint-disable-next-line @angular-eslint/component-selector
The linter wants custom selectors to have a name starting with the name of the project

2022-06-27 20:31 UTC, BrendenMcGrew commented on src/apps/ods-api/src/tag/tag.module.ts
> +export class TagModule {}
You are correct, sir

2022-06-27 20:45 UTC, Mikehickey7 approved these changes

2022-06-27 20:54 UTC, BrendenMcGrew commented on apps/ods/src/app/responses/select-tags/select-tags.component.ts
> +   * @param event
I added two param comments and described what both did

2022-06-27 20:54 UTC, BrendenMcGrew commented on apps/ods/src/app/responses/select-tags/select-tags.component.spec.ts
> +    console.log(expected.length);
Done

2022-06-27 20:55 UTC, BrendenMcGrew commented on apps/ods/src/app/responses/responses.component.ts
> +  //region Main functions
I added the regions back with hashtags

2022-06-28 17:14 UTC, yurisim approved these changes

2022-06-28 17:14 UTC, merged