ODST-147-f-dominos-ticket-system
552ACNS/odst pull request #303
Opened 2022-07-26 15:11 UTC by REDRICK696

# To be Completed by the Pull Requester

### Checklist:

- [x] I have performed a self-review of my code to ensure that unintended code is not introduced.
- [x] I have commented my code, particularly in hard-to-understand areas to ensure that the next group of developers can understand my code.
- [x] I have added tests (if appropriate) that prove my fix/feature functions so that future modifications to the code do not break my additions.

### Description:

Created a page that will allow users to track the progess of a submitted report when they provide a valid report ID. If an improper ID is provided a message will appear telling the user that the ID si not valid.

### Type of change (Pick Any)

2. New feature. Non-breaking change which adds functionality, example: new page on the frontend.

### How Has This Been Tested?

Created two e2e tests that check the progress of a newly created report when it is first created and when the issue is marked as resolved

---

# To be Completed By Reviewers

Reviewer # 01

- [ ] I have performed a review of the code and checked for possible unintentional edits.
- [ ] I concur with the amount of comments made.
- [ ] I concur with the amount of tests made.

Reviewer # 02

- [ ] I have performed a review of the code and checked for possible unintentional edits.
- [ ] I concur with the amount of comments made.
- [ ] I concur with the amount of tests made.

2022-07-28 13:25 UTC, yurisim requested changes
Please resolve issues

2022-07-28 13:25 UTC, yurisim commented on apps/ods-api/src/feedbackResponse/feedbackResponse.service.ts
> +    }
Pull object out of if statements

There's a lot of redundant assignments, if you pull "object" (this is also a horrible name) out you only need to do it once.

Try not to use so many return statements

Grade/firstname/lastname/closedDate are all null initially, there's no need to set them to null for not-reviewed-issues.

console.log should be removed.

2022-07-28 13:25 UTC, yurisim commented on apps/ods/src/app/response-lookup/response-lookup.component.html
> +          by:
Resolved by whomst? This was a requirement on Jira

2022-07-28 13:25 UTC, yurisim commented on apps/ods/src/app/response-lookup/response-lookup.component.ts
> +        this.success = true;
Just create a Tracked Feedback object in the future instead of doing this.

That way you remember you add fields you forgot to add. For example, you forgot to handle a field in tracked-feedback (guess which one! :D ). You would have remembered to handle it, if you used the entity you made in tracked-feedback.entity.ts.

2022-07-28 13:25 UTC, yurisim commented on apps/ods/src/app/response-lookup/response-lookup.module.ts
> +    MatSlideToggleModule,
Why is slide toggle in this? 

Tooltip?

Chips?

Autocomplete?

List?

2022-07-28 13:25 UTC, yurisim commented on apps/ods/src/app/response-lookup/response-lookup.service.spec.ts
> +    controller.verify();
Were any unit tests added at all?

2022-07-28 13:25 UTC, yurisim commented on package.json
> +    "flat": "^5.0.2",
Did you guys even use flat?

2022-07-28 14:49 UTC, yurisim commented on apps/ods/src/app/responses/responses.component.ts
> +    //When false, the actual resolution is set to resolved.
What does this comment mean?

2022-08-16 18:33 UTC, BrendenMcGrew approved these changes

2022-08-16 19:19 UTC, pmeskridge approved these changes

2022-08-17 13:42 UTC, yurisim approved these changes
Adding
```
timeout: 5000
```
Doesn't really fix any of the issues. It happens to cause the tests to pass now but will still result in failures in the future.

https://spin.atomicobject.com/2021/07/20/reduce-flakiness-cypress-tests/

I'll approve it for now but adding arbitrary timeouts (whose default is already really long @ 4 seconds) isn't going to solve problem in the long term.

2022-08-17 13:43 UTC, merged