Migrating and upgrading angular packages
552ACNS/odst pull request #318
Opened 2022-08-15 21:16 UTC by BrendenMcGrew

# To be Completed by the Pull Requester

### Checklist:

- [x] I have performed a self-review of my code to ensure that unintended code is not introduced.
- [x] I have commented my code, particularly in hard-to-understand areas to ensure that the next group of developers can understand my code.
- [x] I have added tests (if appropriate) that prove my fix/feature functions so that future modifications to the code do not break my additions.

### Description:

Upgraded any packages that wouldn't cause a breaking change

### Type of change (Pick Any)

Upgrading packages

### How Has This Been Tested?

N/A

---

# To be Completed By Reviewers

Reviewer # 01

- [ ] I have performed a review of the code and checked for possible unintentional edits.
- [ ] I concur with the amount of comments made.
- [ ] I concur with the amount of tests made.

Reviewer # 02

- [ ] I have performed a review of the code and checked for possible unintentional edits.
- [ ] I concur with the amount of comments made.
- [ ] I concur with the amount of tests made.

2022-08-16 19:13 UTC, pmeskridge approved these changes

2022-08-18 14:27 UTC, yurisim requested changes

2022-08-18 14:27 UTC, yurisim commented on apps/ods/src/app/responses/select-tags/select-tags.component.ts
> +        //Checks that the data is false but not null.
Are you sure this is correct? Is data ever returning false is there's an error?

2022-08-18 14:42 UTC, yurisim submitted a review, later dismissed

2022-08-18 14:42 UTC, yurisim commented on docs/how-tos.md
> +2. If migrations are needed, make sure to run `yarn nx migrate --run-migrations`. ONLY IF migrations are needed.
step 2 should be after "follow the instructions in the terminal"

2022-08-19 17:05 UTC, BrendenMcGrew commented on apps/ods/src/app/responses/select-tags/select-tags.component.ts
> +        //Checks that the data is false but not null.
No, because I don't want it to do anything.

2022-08-24 15:46 UTC, BrendenMcGrew commented on docs/how-tos.md
> +2. If migrations are needed, make sure to run `yarn nx migrate --run-migrations`. ONLY IF migrations are needed.
Fixed by moving the steps after that to step 3.

2022-08-30 18:18 UTC, REDRICK696 approved these changes

2022-09-06 14:18 UTC, merged