Odst 243 fe create angular comment component
552ACNS/odst pull request #376
Opened 2022-11-21 16:46 UTC by Andydawg313

# To be Completed by the Pull Requester

### Checklist:

- [x] I have performed a self-review of my code to ensure that unintended code is not introduced.
- [x] I have commented my code, particularly in hard-to-understand areas to ensure that the next group of developers can understand my code.
- [x] I have added tests (if appropriate) that prove my fix/feature functions so that future modifications to the code do not break my additions.

### Description:

Componentized the comment code to make it reusable

### Type of change (Pick Any)

2. New feature. Non-breaking change which adds functionality, example: new page on the frontend.

### How Has This Been Tested?

Wrote FE tests to ensure it functions properly

---

# To be Completed By Reviewers

Reviewer # 01

- [ ] I have performed a review of the code and checked for possible unintentional edits.
- [ ] I concur with the amount of comments made.
- [ ] I concur with the amount of tests made.

Reviewer # 02

- [ ] I have performed a review of the code and checked for possible unintentional edits.
- [ ] I concur with the amount of comments made.
- [ ] I concur with the amount of tests made.

2022-11-22 20:32 UTC, yurisim requested changes
See requests, feedback, overall good :)

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/components/comments/comments.component.spec.ts
> +  it('should create', () => {
comment or delete the truthy test out. it blocks transparent coverage.

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/components/comments/comments.component.spec.ts
> +    expect(commentElements).toBeTruthy();
should this test be removed given our previous conversation about arrays being truthy?

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/components/comments/comments.component.spec.ts
> +
This is good logic :)

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/components/comments/comments.component.spec.ts
> +      // The author name is displayed in a p with css of `text-xs`
does this comment match the code below?

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/components/comments/comments.component.spec.ts
> +      // The author name is displayed in a p with css of `text-xs`
does this comment match the code below.

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/components/comments/comments.component.spec.ts
> +    it('should display the time below the comments when a different user made the previous', () => {
whenever you have repetitive tests like this, just make a method with parameters and call that method.

I don't expect you to change it, just know that it is a thing.

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/components/comments/comments.component.ts
> +    console.log('CommentsComponent');
do you need on init or the constructor?

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/components/comments/comments.component.ts
> +    console.log('CommentsComponent');
otherwise just remove them

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/responses/responses.component.html
> +      <!-- Comments Section -->
cllleaaan

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/responses/responses.component.ts
> +  async submitComment(comment: string): Promise<void> {
is this trimmed earlier?

2022-11-22 20:32 UTC, yurisim commented on apps/ods/src/app/responses/responses.component.ts
> +  async submitComment(comment: string): Promise<void> {
looks like the trim was removed.

Why is submit comment now a method with parameters rather than a method that just uses this.comment?

2022-11-23 14:57 UTC, yurisim approved these changes

2022-11-23 15:10 UTC, pmeskridge approved these changes

2022-11-23 16:29 UTC, merged